### ISSUE TITLE
License

### ISSUE THREAD

**Issue by apla** [isdampe/BosonEditorExperimental#6]
Hi!

Can you specify a license for this project? Can it be highly permissive, like MIT?

I want to make very simple IDE for the 3D models. Like this plugin, but standalone: https://atom.io/packages/atom-jscad

Your project already have plugin system and works with codemirror which is great.

**Comment by isdampe** [comment]
Sure, added in 2f2cdbd

Keep in mind this was an experimental application and hasn't been touched for a couple of years ;)
